language: ruby
bundler_args: --without development
rvm:
  - 2.2.0
before_script:
  - cp config/database.yml.example config/database.yml
script:
  - bundle exec rspec spec
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: M2Mhwt7nSlgO/p8+kivByb3U123ZGhfzyBGmclRukKaxmFzGESliV0+51bbkCAPllEzpejsToy/XK4KZZm2rmThdGw4dVuZ7NaYwKEHjQjIEKTB7FdYTPIyNjSj3Ma3AKhhF7n8GQ6TrzAph783Rn+bPgPFoeMOYyhfza6bneHY=
  app: uj-survey
  on:
    repo: pboksz/uj-survey
notifications:
  email: false
